[flyway]
locations = ["filesystem:migrations"]

[environments.default]
locations = ["filesystem:migrations"]
url = "jdbc:postgresql://localhost:5432/postgres"
user = "postgres"
password = "mysecretpassword"